export const languages = [
    'text',
    'markdown',
    'typescript',
    'javascript',
    'css',
    'go',
    'python',
    'lua',
    'csharp',
    'yaml',
    'xml',
    'c',
    'rust',
]

export const extMap: Record<string, string> = {
    text: 'txt',
    markdown: 'md',
    typescript: 'ts',
    javascript: 'js',
    css: 'css',
    go: 'go',
    python: 'py',
    lua: 'lua',
    csharp: 'cs',
    yaml: 'yml',
    xml: 'xml',
    c: 'c',
    rust: 'rs',
}
